#!/usr/bin/env groovy
pipeline {
  agent any
  tools {nodejs "latest"}
  stages {
    stage('preflight') {
      steps {
        echo sh(returnStdout: true, script: 'env')
        sh 'node -v'
      }
    }
    stage('build') {
      steps {
        sh 'npm --version'
        dir('frontend') {
          sh 'npm install chromium'
          sh 'npm install'
        }
      }
    }
    stage('test') {
      steps {
        dir('frontend') {
          sh 'npm run listTestCafeBrowsers'
          sh 'npm run studentFilloutAndActivatePenRequest'
        }
      }
    }
  }
}