name: Daily Smoke Test Test Environment
on:
  schedule:
    # Scheduled job to run every day at 6 am PST
    - cron: "0 13 * * *"
  workflow_dispatch:  
jobs:
  Daily_Smoke_Test_Test_Environment:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm install
      - run: npm run getAndDeletePenRequestData
        if: ${{ always() }}
        env:
          TOKEN_ENVIRONMENT: ${{ secrets.DEV_ENVIRONMENT }}
          TOKEN_NAMESPACE: ${{ secrets.TOKEN_NAMESPACE }}
          TOKEN_CLIENT_ID: ${{ secrets.TOKEN_CLIENT_ID }}
          TOKEN_CLIENT_SECRET_DEV: ${{ secrets.TOKEN_CLIENT_SECRET_DEV }}
          DELETE_DIGITAL_ID: ${{secrets.TRUE}}
          PEN_NUMBER: ${{ secrets.PEN_NUMBER }}
          PEN_REQUEST_USER_TYPE: ${{ secrets.USER_TYPE_BCEID }}
      - run: npm run getAndDeleteUmpRequestData
        if: ${{ always() }}
        env:
          TOKEN_ENVIRONMENT: ${{ secrets.DEV_ENVIRONMENT }}
          TOKEN_NAMESPACE: ${{ secrets.TOKEN_NAMESPACE }}
          TOKEN_CLIENT_ID: ${{ secrets.TOKEN_CLIENT_ID }}
          TOKEN_CLIENT_SECRET_DEV: ${{ secrets.TOKEN_CLIENT_SECRET_DEV }}
          PEN_NUMBER: ${{ secrets.PEN_NUMBER }}

      - run: npm run staffRequestForMoreInfoAndRejectOnPen
        if: ${{ always() }}
        env:
          PENEMAIL_USER: ${{ secrets.PENEMAIL_USER }}
          PENEMAIL_PASS: ${{ secrets.PENEMAIL_PASS }}
          BCEID_USER: ${{ secrets.BCEID_USER }}
          BCEID_PASS: ${{ secrets.BCEID_PASS }}
          PEN_ENVIRONMENT: ${{ secrets.TEST_ENVIRONMENT }}
          PEN_NAMESPACE: ${{ secrets.PEN_NAMESPACE }}
          IDIR_ADMIN_USER: ${{ secrets.IDIR_ADMIN_USER }}
          IDIR_ADMIN_PASS: ${{ secrets.IDIR_ADMIN_PASS }}
          IDIR_READ_ONLY_USER: ${{ secrets.IDIR_READ_ONLY_USER }}
          IDIR_READ_ONLY_PASS: ${{ secrets.IDIR_READ_ONLY_PASS }}
          PEN_NUMBER: ${{ secrets.PEN_NUMBER }}
      - run: npm run getAndDeletePenRequestData
        if: ${{ success() }}
        env:
          TOKEN_ENVIRONMENT: ${{ secrets.DEV_ENVIRONMENT }}
          TOKEN_NAMESPACE: ${{ secrets.TOKEN_NAMESPACE }}
          TOKEN_CLIENT_ID: ${{ secrets.TOKEN_CLIENT_ID }}
          TOKEN_CLIENT_SECRET_DEV: ${{ secrets.TOKEN_CLIENT_SECRET_DEV }}
          DELETE_DIGITAL_ID: ${{secrets.TRUE}}
          PEN_NUMBER: ${{ secrets.PEN_NUMBER }}
          PEN_REQUEST_USER_TYPE: ${{ secrets.USER_TYPE_BCEID }}
          
      - run: npm run staffIssuePenToStudent
        if: ${{ always() }}
        env:
          PENEMAIL_USER: ${{ secrets.PENEMAIL_USER }}
          PENEMAIL_PASS: ${{ secrets.PENEMAIL_PASS }}
          BCEID_USER: ${{ secrets.BCEID_USER }}
          BCEID_PASS: ${{ secrets.BCEID_PASS }}
          PEN_ENVIRONMENT: ${{ secrets.TEST_ENVIRONMENT }}
          PEN_NAMESPACE: ${{ secrets.PEN_NAMESPACE }}
          IDIR_ADMIN_USER: ${{ secrets.IDIR_ADMIN_USER }}
          IDIR_ADMIN_PASS: ${{ secrets.IDIR_ADMIN_PASS }}
          PEN_NUMBER: ${{ secrets.PEN_NUMBER }}
      - run: npm run getAndDeletePenRequestData
        if: ${{ success() }}
        env:
          TOKEN_ENVIRONMENT: ${{ secrets.DEV_ENVIRONMENT }}
          TOKEN_NAMESPACE: ${{ secrets.TOKEN_NAMESPACE }}
          TOKEN_CLIENT_ID: ${{ secrets.TOKEN_CLIENT_ID }}
          TOKEN_CLIENT_SECRET_DEV: ${{ secrets.TOKEN_CLIENT_SECRET_DEV }}
          DELETE_DIGITAL_ID: ${{secrets.TRUE}}
          PEN_NUMBER: ${{ secrets.PEN_NUMBER }}
          PEN_REQUEST_USER_TYPE: ${{ secrets.USER_TYPE_BCEID }}


      - run: npm run staffRequestForMoreInfoAndRejectOnUmp
        if: ${{ always() }}
        env:
          PENEMAIL_USER: ${{ secrets.PENEMAIL_USER }}
          PENEMAIL_PASS: ${{ secrets.PENEMAIL_PASS }}
          BCEID_USER: ${{ secrets.BCEID_USER }}
          BCEID_PASS: ${{ secrets.BCEID_PASS }}
          PEN_ENVIRONMENT: ${{ secrets.TEST_ENVIRONMENT }}
          PEN_NAMESPACE: ${{ secrets.PEN_NAMESPACE }}
          IDIR_ADMIN_USER: ${{ secrets.IDIR_ADMIN_USER }}
          IDIR_ADMIN_PASS: ${{ secrets.IDIR_ADMIN_PASS }}
          IDIR_READ_ONLY_USER: ${{ secrets.IDIR_READ_ONLY_USER }}
          IDIR_READ_ONLY_PASS: ${{ secrets.IDIR_READ_ONLY_PASS }}
          PEN_NUMBER: ${{ secrets.PEN_NUMBER }}
      - run: npm run getAndDeleteUmpRequestData
        if: ${{ success() }}
        env:
          TOKEN_ENVIRONMENT: ${{ secrets.DEV_ENVIRONMENT }}
          TOKEN_NAMESPACE: ${{ secrets.TOKEN_NAMESPACE }}
          TOKEN_CLIENT_ID: ${{ secrets.TOKEN_CLIENT_ID }}
          TOKEN_CLIENT_SECRET_DEV: ${{ secrets.TOKEN_CLIENT_SECRET_DEV }}
          PEN_NUMBER: ${{ secrets.PEN_NUMBER }}

      # - uses: actions/upload-artifact@v2
      #   if: ${{ failure() }}
      #   with:
      #     name: Screenshot
      #     path: D:\a\EDUC-E2E-PEN-REGISTRY\EDUC-E2E-PEN-REGISTRY\frontend\tests\e2e\screenshots\

      - name: Rocket.Chat Notification
        uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@1.1.1
        if: always()
        with:
          type: ${{ job.status }}
          job_name: "Daily Smoke test result of Test environment --->"
          icon_emoji: ":bell:"
          channel: "pen-automation-notifications"
          url: ${{ secrets.ROCKETCHAT_WEBHOOK }}
