name: Journey Builder Navigation Test Test Environment
on:
  schedule:
    # Scheduled job to run every Monday at 7 am
    - cron: "0 14 * * 1"
  workflow_dispatch:  
jobs:
  Journey_Builder_Navigation_Test_Test_Environment:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - run: npm install
      - run: npm run journeyBuilderNavigation
        if: ${{ always() }}
        env:
          BCEID_USER: ${{ secrets.BCEID_USER }}
          BCEID_PASS: ${{ secrets.BCEID_PASS }}
          IDIR_ADMIN_USER: ${{ secrets.IDIR_ADMIN_USER }}
          IDIR_ADMIN_PASS: ${{ secrets.IDIR_ADMIN_PASS }}
          JB_GMP_PAGE_URL: ${{ secrets.JB_GMP_PAGE_URL }}
          JB_UMP_PAGE_URL: ${{ secrets.JB_UMP_PAGE_URL }}
          REGISTER_PAGE_URL: ${{ secrets.REGISTER_PAGE_URL }}
          GMP_PAGE_URL: ${{ secrets.GMP_PAGE_URL }}
          UMP_PAGE_URL: ${{ secrets.UMP_PAGE_URL }}

      # - uses: actions/upload-artifact@v2
      #   if: ${{ failure() }}
      #   with:
      #     name: Screenshot
      #     path: D:\a\EDUC-E2E-PEN-REGISTRY\EDUC-E2E-PEN-REGISTRY\frontend\tests\e2e\screenshots\

      - name: Rocket.Chat Notification
        uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@1.1.1
        if: always()
        with:
          type: ${{ job.status }}
          job_name: "Journey builder navigation test - TEST --->"
          icon_emoji: ":bell:"
          channel: "pen-automation-notifications"
          url: ${{ secrets.ROCKETCHAT_WEBHOOK }}

      - name: Rocket.Chat Notification
        uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@1.1.1
        if:  steps.build.outcome != 'success'
        with:
          type: ${{ job.status }}
          job_name: "Journey builder navigation test - TEST --->"
          icon_emoji: ":bell:"
          channel: "pen-automation-notifications"
          url: ${{ secrets.ROCKETCHAT_WEBHOOK_FAILURES }}