name: Maintenance Page On Test
on: 
  repository_dispatch:
    types: [maintenance-on-test]
  workflow_dispatch:  

jobs:
  MaintenancePageOn_Test:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - run: npm install

      - run: npm run maintenancePageOn
        if: ${{ always() }}
        env:
          PEN_ENVIRONMENT: ${{ secrets.TEST_ENVIRONMENT }}
          PEN_NAMESPACE: ${{ secrets.PEN_NAMESPACE }}
