# This work flow covers staff search for student and edit student details scenarios.
name: Regression Test Test Environment Latest
on:
  repository_dispatch:
    types: [regressionTest-test-environment-latest]
  workflow_dispatch: 
jobs:
  RegressionTest_Test_Environment_Latest:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm install

      - run: npm run staffQuickSearchUpdateAndResetStudentInfo
        if: ${{ always() }}
        env:
          PEN_ENVIRONMENT: ${{ secrets.DEV_ENVIRONMENT }}
          PEN_NAMESPACE: ${{ secrets.PEN_NAMESPACE }}
          IDIR_ADMIN_USER: ${{ secrets.IDIR_ADMIN_USER }}
          IDIR_ADMIN_PASS: ${{ secrets.IDIR_ADMIN_PASS }}
          PEN_NUMBER: ${{ secrets.PEN_NUMBER }}
          PEN_MERGED: ${{ secrets.PEN_MERGED }}

      # - run: npm run verifyValidationErrorsAndCreateNewPen
      #   if: ${{ always() }}
      #   env:
      #     PEN_ENVIRONMENT: ${{ secrets.DEV_ENVIRONMENT }}
      #     PEN_NAMESPACE: ${{ secrets.PEN_NAMESPACE }}
      #     IDIR_ADMIN_USER: ${{ secrets.IDIR_ADMIN_USER }}
      #     IDIR_ADMIN_PASS: ${{ secrets.IDIR_ADMIN_PASS }}

      # - run: npm run getAndDeleteStudentData
      #   if: ${{ always() }}
      #   env:
      #     TOKEN_ENVIRONMENT: ${{ secrets.TOOLS_ENVIRONMENT }}
      #     TOKEN_NAMESPACE: ${{ secrets.TOKEN_NAMESPACE }}
      #     TOKEN_CLIENT_ID: ${{ secrets.TOKEN_CLIENT_ID }}
      #     TOKEN_CLIENT_SECRET_TOOLS: ${{ secrets.TOKEN_CLIENT_SECRET_TOOLS }}

      - run: npm run comparePens
        if: ${{ always() }}
        env:
          PEN_ENVIRONMENT: ${{ secrets.DEV_ENVIRONMENT }}
          PEN_NAMESPACE: ${{ secrets.PEN_NAMESPACE }}
          IDIR_ADMIN_USER: ${{ secrets.IDIR_ADMIN_USER }}
          IDIR_ADMIN_PASS: ${{ secrets.IDIR_ADMIN_PASS }}
          PEN_NUMBER: ${{ secrets.PEN_NUMBER }}
          PEN_MERGED: ${{ secrets.PEN_MERGED }}
          
      # - uses: actions/upload-artifact@v2
      #   if: ${{ failure() }}
      #   with:
      #     name: Screenshot
      #     path: D:\a\EDUC-E2E-PEN-REGISTRY\EDUC-E2E-PEN-REGISTRY\frontend\tests\e2e\screenshots\

      - name: Rocket.Chat Notification
        uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@1.1.1
        if: always()
        with:
          type: ${{ job.status }}
          job_name: "DEV Environment Regression Latest Test result --->"
          icon_emoji: ":bell:"
          channel: "pen-automation-notifications"
          url: ${{ secrets.ROCKETCHAT_WEBHOOK }}
           