# This work flow covers staff search for student and edit student details scenarios.
name: Regression Test Test Environment Latest
on:
  repository_dispatch:
    types: [regressionTest-test-environment-latest]
  workflow_dispatch:
jobs:
  RegressionTest_Test_Environment_Latest:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm install

      - run: npm run staffQuickSearchUpdateAndResetStudentInfo
        if: ${{ always() }}
        env:
          PEN_ENVIRONMENT: ${{ secrets.TEST_ENVIRONMENT }}
          PEN_NAMESPACE: ${{ secrets.PEN_NAMESPACE }}
          IDIR_ADMIN_USER: ${{ secrets.IDIR_ADMIN_USER }}
          IDIR_ADMIN_PASS: ${{ secrets.IDIR_ADMIN_PASS }}
          PEN_NUMBER: ${{ secrets.PEN_NUMBER }}
          PEN_MERGED: ${{ secrets.PEN_MERGED }}

      - run: npm run comparePens
        if: ${{ always() }}
        env:
          PEN_ENVIRONMENT: ${{ secrets.TEST_ENVIRONMENT }}
          PEN_NAMESPACE: ${{ secrets.PEN_NAMESPACE }}
          IDIR_ADMIN_USER: ${{ secrets.IDIR_ADMIN_USER }}
          IDIR_ADMIN_PASS: ${{ secrets.IDIR_ADMIN_PASS }}
          PEN_NUMBER: ${{ secrets.PEN_NUMBER }}
          PEN_MERGED: ${{ secrets.PEN_MERGED }}

      # - run: npm run deleteStudent
      #   if: ${{ always() }}
      #   env:
      #     TOKEN_ENVIRONMENT: ${{ secrets.DEV_ENVIRONMENT }}
      #     TOKEN_NAMESPACE: ${{ secrets.TOKEN_NAMESPACE }}
      #     TOKEN_CLIENT_ID: ${{ secrets.TOKEN_CLIENT_ID }}
      #     TOKEN_CLIENT_SECRET_DEV: ${{ secrets.TOKEN_CLIENT_SECRET_DEV }}
      #     DELETE_DIGITAL_ID: ${{secrets.TRUE}}
      #     PEN_STUDENT_HISTORY: ${{ secrets.PEN_STUDENT_HISTORY }}

      - run: npm run insertStudent
        if: ${{ always() }}
        env:
          TOKEN_ENVIRONMENT: ${{ secrets.DEV_ENVIRONMENT }}
          TOKEN_NAMESPACE: ${{ secrets.TOKEN_NAMESPACE }}
          TOKEN_CLIENT_ID: ${{ secrets.TOKEN_CLIENT_ID }}
          TOKEN_CLIENT_SECRET_DEV: ${{ secrets.TOKEN_CLIENT_SECRET_DEV }}
          DELETE_DIGITAL_ID: ${{secrets.TRUE}}
          PEN_STUDENT_HISTORY: ${{ secrets.PEN_STUDENT_HISTORY }}

      - run: npm run studentAuditHistory
        if: ${{ always() }}
        env:
          PEN_ENVIRONMENT: ${{ secrets.TEST_ENVIRONMENT }}
          PEN_NAMESPACE: ${{ secrets.PEN_NAMESPACE }}
          IDIR_ADMIN_USER: ${{ secrets.IDIR_ADMIN_USER }}
          IDIR_ADMIN_PASS: ${{ secrets.IDIR_ADMIN_PASS }}
          PEN_STUDENT_HISTORY: ${{ secrets.PEN_STUDENT_HISTORY }}

      - run: npm run deleteStudent
        if: ${{ always() }}
        env:
          TOKEN_ENVIRONMENT: ${{ secrets.DEV_ENVIRONMENT }}
          TOKEN_NAMESPACE: ${{ secrets.TOKEN_NAMESPACE }}
          TOKEN_CLIENT_ID: ${{ secrets.TOKEN_CLIENT_ID }}
          TOKEN_CLIENT_SECRET_DEV: ${{ secrets.TOKEN_CLIENT_SECRET_DEV }}
          DELETE_DIGITAL_ID: ${{secrets.TRUE}}
          PEN_STUDENT_HISTORY: ${{ secrets.PEN_STUDENT_HISTORY }}

      - run: npm run insertTwinAndMergeStudents
        if: ${{ always() }}
        env:
          TOKEN_ENVIRONMENT: ${{ secrets.DEV_ENVIRONMENT }}
          TOKEN_NAMESPACE: ${{ secrets.TOKEN_NAMESPACE }}
          TOKEN_CLIENT_ID: ${{ secrets.TOKEN_CLIENT_ID }}
          TOKEN_CLIENT_SECRET_DEV: ${{ secrets.TOKEN_CLIENT_SECRET_DEV }}
          DELETE_DIGITAL_ID: ${{secrets.TRUE}}
          TWIN_ONE_PEN: ${{ secrets.TWIN_ONE_PEN }}
          TWIN_TWO_PEN: ${{ secrets.TWIN_TWO_PEN }}
          TWIN_THREE_PEN: ${{ secrets.TWIN_THREE_PEN }}
          MERGE_ONE_PEN: ${{ secrets.MERGE_ONE_PEN }}
          MERGE_TWO_PEN: ${{ secrets.MERGE_TWO_PEN }}
          MERGE_THREE_PEN: ${{ secrets.MERGE_THREE_PEN }}

      - run: npm run twinStudents
        if: ${{ always() }}
        env:
          PEN_ENVIRONMENT: ${{ secrets.TEST_ENVIRONMENT }}
          PEN_NAMESPACE: ${{ secrets.PEN_NAMESPACE }}
          IDIR_ADMIN_USER: ${{ secrets.IDIR_ADMIN_USER }}
          IDIR_ADMIN_PASS: ${{ secrets.IDIR_ADMIN_PASS }}
          TWIN_ONE_PEN: ${{ secrets.TWIN_ONE_PEN }}
          TWIN_TWO_PEN: ${{ secrets.TWIN_TWO_PEN }}
          TWIN_THREE_PEN: ${{ secrets.TWIN_THREE_PEN }}

      - run: npm run deleteTwinAndMergeStudents
        if: ${{ always() }}
        env:
          TOKEN_ENVIRONMENT: ${{ secrets.DEV_ENVIRONMENT }}
          TOKEN_NAMESPACE: ${{ secrets.TOKEN_NAMESPACE }}
          TOKEN_CLIENT_ID: ${{ secrets.TOKEN_CLIENT_ID }}
          TOKEN_CLIENT_SECRET_DEV: ${{ secrets.TOKEN_CLIENT_SECRET_DEV }}
          DELETE_DIGITAL_ID: ${{secrets.TRUE}}
          TWIN_ONE_PEN: ${{ secrets.TWIN_ONE_PEN }}
          TWIN_TWO_PEN: ${{ secrets.TWIN_TWO_PEN }}
          TWIN_THREE_PEN: ${{ secrets.TWIN_THREE_PEN }}
          MERGE_ONE_PEN: ${{ secrets.MERGE_ONE_PEN }}
          MERGE_TWO_PEN: ${{ secrets.MERGE_TWO_PEN }}
          MERGE_THREE_PEN: ${{ secrets.MERGE_THREE_PEN }}


      # - uses: actions/upload-artifact@v2
      #   if: ${{ failure() }}
      #   with:
      #     name: Screenshot
      #     path: D:\a\EDUC-E2E-PEN-REGISTRY\EDUC-E2E-PEN-REGISTRY\frontend\tests\e2e\screenshots\

      - name: Rocket.Chat Notification
        uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@1.1.1
        if: always()
        with:
          type: ${{ job.status }}
          job_name: "TEST Environment Regression Latest Test result --->"
          icon_emoji: ":bell:"
          channel: "pen-automation-notifications"
          url: ${{ secrets.ROCKETCHAT_WEBHOOK }}
