# This workflow covers request information, reject,complete, unlink, Readonly roles for Pen Request and
# request information, reject,complete, Readonly roles for Ump Request. (Dev environment)
name: Regression Test Dev Environment
on:
  repository_dispatch:
    types: [regressionTest-dev-environment]
  workflow_dispatch: 
jobs:
  RegressionTest_Dev_Environment:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm install
      - run: $env:NODE_OPTIONS='--max-http-header-size=17000'
      
      - run: npm run getAndDeletePenRequestData
        if: ${{ always() }}
        env:
          TOKEN_ENVIRONMENT: ${{ secrets.TOOLS_ENVIRONMENT }}
          TOKEN_NAMESPACE: ${{ secrets.TOKEN_NAMESPACE }}
          TOKEN_CLIENT_ID: ${{ secrets.TOKEN_CLIENT_ID }}
          TOKEN_CLIENT_SECRET_TOOLS: ${{ secrets.TOKEN_CLIENT_SECRET_TOOLS }}
          DELETE_DIGITAL_ID: ${{secrets.TRUE}}
          PEN_NUMBER: ${{ secrets.PEN_NUMBER }}
          PEN_REQUEST_USER_TYPE: ${{ secrets.USER_TYPE_BCEID }}

      - run: npm run staffRequestForMoreInfoAndRejectOnPen
        if: ${{ always() }}
        env:
          PENEMAIL_USER: ${{ secrets.PENEMAIL_USER }}
          PENEMAIL_PASS: ${{ secrets.PENEMAIL_PASS }}
          BCEID_USER: ${{ secrets.BCEID_USER }}
          BCEID_PASS: ${{ secrets.BCEID_PASS }}
          PEN_ENVIRONMENT: ${{ secrets.DEV_ENVIRONMENT }}
          PEN_NAMESPACE: ${{ secrets.PEN_NAMESPACE }}
          IDIR_ADMIN_USER: ${{ secrets.IDIR_ADMIN_USER }}
          IDIR_ADMIN_PASS: ${{ secrets.IDIR_ADMIN_PASS }}
          IDIR_READ_ONLY_USER: ${{ secrets.IDIR_READ_ONLY_USER }}
          IDIR_READ_ONLY_PASS: ${{ secrets.IDIR_READ_ONLY_PASS }}
          PEN_NUMBER: ${{ secrets.PEN_NUMBER }}
          STUDENT_ENTRY_POINT: ${{secrets.STUDENT_ENTRY_POINT_LANDING_PAGE}}
      - run: npm run getAndDeletePenRequestData
        if: ${{ always() }}
        env:
          TOKEN_ENVIRONMENT: ${{ secrets.TOOLS_ENVIRONMENT }}
          TOKEN_NAMESPACE: ${{ secrets.TOKEN_NAMESPACE }}
          TOKEN_CLIENT_ID: ${{ secrets.TOKEN_CLIENT_ID }}
          TOKEN_CLIENT_SECRET_TOOLS: ${{ secrets.TOKEN_CLIENT_SECRET_TOOLS }}
          DELETE_DIGITAL_ID: ${{secrets.TRUE}}
          PEN_NUMBER: ${{ secrets.PEN_NUMBER }}
          PEN_REQUEST_USER_TYPE: ${{ secrets.USER_TYPE_BCEID }}

      - run: npm run getAndDeleteUmpRequestData
        if: ${{ always() }}
        env:
          TOKEN_ENVIRONMENT: ${{ secrets.TOOLS_ENVIRONMENT }}
          TOKEN_NAMESPACE: ${{ secrets.TOKEN_NAMESPACE }}
          TOKEN_CLIENT_ID: ${{ secrets.TOKEN_CLIENT_ID }}
          TOKEN_CLIENT_SECRET_TOOLS: ${{ secrets.TOKEN_CLIENT_SECRET_TOOLS }}
          PEN_NUMBER: ${{ secrets.PEN_NUMBER }}

      - run: npm run staffRequestForMoreInfoAndRejectOnUmp
        if: ${{ always() }}
        env:
          PENEMAIL_USER: ${{ secrets.PENEMAIL_USER }}
          PENEMAIL_PASS: ${{ secrets.PENEMAIL_PASS }}
          BCEID_USER: ${{ secrets.BCEID_USER }}
          BCEID_PASS: ${{ secrets.BCEID_PASS }}
          PEN_ENVIRONMENT: ${{ secrets.DEV_ENVIRONMENT }}
          PEN_NAMESPACE: ${{ secrets.PEN_NAMESPACE }}
          IDIR_ADMIN_USER: ${{ secrets.IDIR_ADMIN_USER }}
          IDIR_ADMIN_PASS: ${{ secrets.IDIR_ADMIN_PASS }}
          IDIR_READ_ONLY_USER: ${{ secrets.IDIR_READ_ONLY_USER }}
          IDIR_READ_ONLY_PASS: ${{ secrets.IDIR_READ_ONLY_PASS }}
          PEN_NUMBER: ${{ secrets.PEN_NUMBER }}
          STUDENT_ENTRY_POINT: ${{secrets.STUDENT_ENTRY_POINT_LANDING_PAGE}}
      - run: npm run getAndDeleteUmpRequestData
        if: ${{ always() }}
        env:
          TOKEN_ENVIRONMENT: ${{ secrets.TOOLS_ENVIRONMENT }}
          TOKEN_NAMESPACE: ${{ secrets.TOKEN_NAMESPACE }}
          TOKEN_CLIENT_ID: ${{ secrets.TOKEN_CLIENT_ID }}
          TOKEN_CLIENT_SECRET_TOOLS: ${{ secrets.TOKEN_CLIENT_SECRET_TOOLS }}
          PEN_NUMBER: ${{ secrets.PEN_NUMBER }}

      - run: npm run studentSubmitGenderChangeAfterPenCompleteGetsCompleted
        if: ${{ always() }}
        env:
          PENEMAIL_USER: ${{ secrets.PENEMAIL_USER }}
          PENEMAIL_PASS: ${{ secrets.PENEMAIL_PASS }}
          BCEID_USER: ${{ secrets.BCEID_USER }}
          BCEID_PASS: ${{ secrets.BCEID_PASS }}
          PEN_ENVIRONMENT: ${{ secrets.DEV_ENVIRONMENT }}
          PEN_NAMESPACE: ${{ secrets.PEN_NAMESPACE }}
          IDIR_ADMIN_USER: ${{ secrets.IDIR_ADMIN_USER }}
          IDIR_ADMIN_PASS: ${{ secrets.IDIR_ADMIN_PASS }}
          PEN_NUMBER: ${{ secrets.PEN_NUMBER }}
          STUDENT_ENTRY_POINT: ${{secrets.STUDENT_ENTRY_POINT_LANDING_PAGE}}
      - run: npm run getAndDeletePenRequestData
        if: ${{ always() }}
        env:
          TOKEN_ENVIRONMENT: ${{ secrets.TOOLS_ENVIRONMENT }}
          TOKEN_NAMESPACE: ${{ secrets.TOKEN_NAMESPACE }}
          TOKEN_CLIENT_ID: ${{ secrets.TOKEN_CLIENT_ID }}
          TOKEN_CLIENT_SECRET_TOOLS: ${{ secrets.TOKEN_CLIENT_SECRET_TOOLS }}
          DELETE_DIGITAL_ID: ${{secrets.TRUE}}
          PEN_NUMBER: ${{ secrets.PEN_NUMBER }}
          PEN_REQUEST_USER_TYPE: ${{ secrets.USER_TYPE_BCEID }}
      - run: npm run getAndDeleteUmpRequestData
        if: ${{ always() }}
        env:
          TOKEN_ENVIRONMENT: ${{ secrets.TOOLS_ENVIRONMENT }}
          TOKEN_NAMESPACE: ${{ secrets.TOKEN_NAMESPACE }}
          TOKEN_CLIENT_ID: ${{ secrets.TOKEN_CLIENT_ID }}
          TOKEN_CLIENT_SECRET_TOOLS: ${{ secrets.TOKEN_CLIENT_SECRET_TOOLS }}
          PEN_NUMBER: ${{ secrets.PEN_NUMBER }}
          
      # - uses: actions/upload-artifact@v2
      #   if: ${{ failure() }}
      #   with:
      #     name: Screenshot
      #     path: D:\a\EDUC-E2E-PEN-REGISTRY\EDUC-E2E-PEN-REGISTRY\frontend\tests\e2e\screenshots\

      - name: Rocket.Chat Notification
        uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@1.1.1
        if: success()
        with:
          type: ${{ job.status }}
          job_name: "DEV Environment Regression Test result --->"
          icon_emoji: ":bell:"
          channel: "pen-automation-notifications"
          url: ${{ secrets.ROCKETCHAT_WEBHOOK }}
