name: Saga Part One Dev Environment
on:
  repository_dispatch:
    types: [saga-part-one-dev-environment]
  workflow_dispatch:  

jobs:
  Saga_Part_One_Dev_Environment:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm install

      - run: npm run getAndDeletePenRequestData
        if: ${{ always() }}
        env:
          TOKEN_ENVIRONMENT: ${{ secrets.DEV_ENVIRONMENT }}
          TOKEN_NAMESPACE: ${{ secrets.TOKEN_NAMESPACE }}
          TOKEN_CLIENT_ID: ${{ secrets.TOKEN_CLIENT_ID }}
          TOKEN_CLIENT_SECRET_DEV: ${{ secrets.TOKEN_CLIENT_SECRET_DEV }}
          DELETE_DIGITAL_ID: ${{secrets.FALSE}}
          PEN_NUMBER: ${{ secrets.PEN_NUMBER }}
          PEN_REQUEST_USER_TYPE: ${{ secrets.USER_TYPE_BCEID }}
      - run: npm run insertAndUpdatePenRequestData
        if: ${{ always() }}
        env:
          TOKEN_ENVIRONMENT: ${{ secrets.DEV_ENVIRONMENT }}
          TOKEN_NAMESPACE: ${{ secrets.TOKEN_NAMESPACE }}
          TOKEN_CLIENT_ID: ${{ secrets.TOKEN_CLIENT_ID }}
          TOKEN_CLIENT_SECRET_DEV: ${{ secrets.TOKEN_CLIENT_SECRET_DEV }}
          BCEID_DIGITAL_ID_DEV: ${{ secrets.BCEID_DIGITAL_ID_DEV }}

      - run: npm run verifySagaTestCase
        if: ${{ always() }}
        env:
          PEN_ENVIRONMENT: ${{ secrets.DEV_ENVIRONMENT }}
          PEN_NAMESPACE: ${{ secrets.PEN_NAMESPACE }}
          IDIR_ADMIN_USER: ${{ secrets.IDIR_ADMIN_USER_2 }}
          IDIR_ADMIN_PASS: ${{ secrets.IDIR_ADMIN_PASS }}

      - run: npm run getAndDeletePenRequestData
        if: ${{ always() }}
        env:
          TOKEN_ENVIRONMENT: ${{ secrets.DEV_ENVIRONMENT }}
          TOKEN_NAMESPACE: ${{ secrets.TOKEN_NAMESPACE }}
          TOKEN_CLIENT_ID: ${{ secrets.TOKEN_CLIENT_ID }}
          TOKEN_CLIENT_SECRET_DEV: ${{ secrets.TOKEN_CLIENT_SECRET_DEV }}
          DELETE_DIGITAL_ID: ${{secrets.FALSE}}
          PEN_NUMBER: ${{ secrets.PEN_NUMBER }}
          PEN_REQUEST_USER_TYPE: ${{ secrets.USER_TYPE_BCEID }}
          
      # - uses: actions/upload-artifact@v2
      #   if: ${{ failure() }}
      #   with:
      #     name: Screenshot
      #     path: D:\a\EDUC-E2E-PEN-REGISTRY\EDUC-E2E-PEN-REGISTRY\frontend\tests\e2e\screenshots\

      - name: Rocket.Chat Notification
        uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@1.1.1
        if: always()
        with:
          type: ${{ job.status }}
          job_name: "Saga verification result of DEV Environment --->"
          icon_emoji: ":bell:"
          channel: "pen-automation-notifications"
          url: ${{ secrets.ROCKETCHAT_WEBHOOK }}