name: Smoke Test Student Profile Test Environment
on:
  repository_dispatch:
    types: [smoke-test-student-profile-test-environment]
  workflow_dispatch: 

jobs:
  Smoke_Test_Student_Profile_Test_Environment:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v2

      - name: Cache Node Modules
        uses: actions/cache@v1
        env:
          cahce-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - run: npm install

      - run: npm run getAndDeletePenRequestData
        if: ${{ always() }}
        env:
          TOKEN_ENVIRONMENT: ${{ secrets.TEST_ENVIRONMENT }}
          TOKEN_NAMESPACE: ${{ secrets.TOKEN_NAMESPACE }}
          TOKEN_CLIENT_ID: ${{ secrets.TOKEN_CLIENT_ID }}
          TOKEN_CLIENT_SECRET_TEST: ${{ secrets.TOKEN_CLIENT_SECRET_TEST }}
          DELETE_DIGITAL_ID: ${{secrets.TRUE}}
          PEN_NUMBER: ${{ secrets.PEN_NUMBER }}
          PEN_REQUEST_USER_TYPE: ${{ secrets.USER_TYPE_BCEID }}
      - run: npm run studentFilloutAndActivatePenRequest
        if: ${{ always() }}
        env:
          PENEMAIL_USER: ${{ secrets.PENEMAIL_USER }}
          PENEMAIL_PASS: ${{ secrets.PENEMAIL_PASS }}
          BCEID_USER: ${{ secrets.BCEID_USER }}
          BCEID_PASS: ${{ secrets.BCEID_PASS }}
          PEN_ENVIRONMENT: ${{ secrets.TEST_ENVIRONMENT }}
          PEN_NAMESPACE: ${{ secrets.PEN_NAMESPACE }}
          PEN_NUMBER: ${{ secrets.PEN_NUMBER }}
      - run: npm run getAndDeletePenRequestData
        if: ${{ always() }}
        env:
          TOKEN_ENVIRONMENT: ${{ secrets.TEST_ENVIRONMENT }}
          TOKEN_NAMESPACE: ${{ secrets.TOKEN_NAMESPACE }}
          TOKEN_CLIENT_ID: ${{ secrets.TOKEN_CLIENT_ID }}
          TOKEN_CLIENT_SECRET_TEST: ${{ secrets.TOKEN_CLIENT_SECRET_TEST }}
          DELETE_DIGITAL_ID: ${{secrets.TRUE}}
          PEN_NUMBER: ${{ secrets.PEN_NUMBER }}
          PEN_REQUEST_USER_TYPE: ${{ secrets.USER_TYPE_BCEID }}
      - run: npm run getAndDeleteUmpRequestData
        if: ${{ always() }}
        env:
          TOKEN_ENVIRONMENT: ${{ secrets.TEST_ENVIRONMENT }}
          TOKEN_NAMESPACE: ${{ secrets.TOKEN_NAMESPACE }}
          TOKEN_CLIENT_ID: ${{ secrets.TOKEN_CLIENT_ID }}
          TOKEN_CLIENT_SECRET_TEST: ${{ secrets.TOKEN_CLIENT_SECRET_TEST }}
          PEN_NUMBER: ${{ secrets.PEN_NUMBER }}
      - run: npm run studentFilloutAndActivateUmpRequest
        if: ${{ always() }}
        env:
          PENEMAIL_USER: ${{ secrets.PENEMAIL_USER }}
          PENEMAIL_PASS: ${{ secrets.PENEMAIL_PASS }}
          BCEID_USER: ${{ secrets.BCEID_USER }}
          BCEID_PASS: ${{ secrets.BCEID_PASS }}
          PEN_ENVIRONMENT: ${{ secrets.TEST_ENVIRONMENT }}
          PEN_NAMESPACE: ${{ secrets.PEN_NAMESPACE }}
          PEN_NUMBER: ${{ secrets.PEN_NUMBER }}
      - run: npm run getAndDeleteUmpRequestData
        if: ${{ always() }}
        env:
          TOKEN_ENVIRONMENT: ${{ secrets.TEST_ENVIRONMENT }}
          TOKEN_NAMESPACE: ${{ secrets.TOKEN_NAMESPACE }}
          TOKEN_CLIENT_ID: ${{ secrets.TOKEN_CLIENT_ID }}
          TOKEN_CLIENT_SECRET_TEST: ${{ secrets.TOKEN_CLIENT_SECRET_TEST }}
          PEN_NUMBER: ${{ secrets.PEN_NUMBER }}
      # - uses: actions/upload-artifact@v2
      #   if: ${{ failure() }}
      #   with:
      #     name: Screenshot
      #     path: D:\a\EDUC-E2E-PEN-REGISTRY\EDUC-E2E-PEN-REGISTRY\frontend\tests\e2e\screenshots\

      - name: Rocket.Chat Notification
        uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@1.1.1
        if: always()
        with:
          type: ${{ job.status }}
          job_name: "Smoke Test result of Student Profile in Test Environment --->"
          icon_emoji: ":bell:"
          channel: "pen-automation-notifications"
          url: ${{ secrets.ROCKETCHAT_WEBHOOK }}
