name: Unauthorized Access Test Environment
on:
  repository_dispatch:
    types: [unauthorized-access-test-environment]
  workflow_dispatch: 
jobs:
  Regression:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - run: npm install

      - run: npm run unauthorizedAccess
        if: ${{ always() }}
        env:
          PEN_ENVIRONMENT: ${{ secrets.TEST_ENVIRONMENT }}
          PEN_NAMESPACE: ${{ secrets.PEN_NAMESPACE }}
          IDIR_READ_ONLY_USER: ${{ secrets.IDIR_READ_ONLY_USER }}
          IDIR_READ_ONLY_PASS: ${{ secrets.IDIR_READ_ONLY_PASS }}

      # - uses: actions/upload-artifact@v2
      #   if: ${{ failure() }}
      #   with:
      #     name: Screenshot
      #     path: D:\a\EDUC-E2E-PEN-REGISTRY\EDUC-E2E-PEN-REGISTRY\frontend\tests\e2e\screenshots\

      - name: Rocket.Chat Notification
        uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@1.1.1
        if: success()
        with:
          type: ${{ job.status }}
          job_name: "Unauthorized Access test - TEST --->"
          icon_emoji: ":bell:"
          channel: "pen-automation-notifications"
          url: ${{ secrets.ROCKETCHAT_WEBHOOK }}

      - name: Rocket.Chat Notification
        uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@1.1.1
        if:  failure()
        with:
          type: ${{ job.status }}
          job_name: "Unauthorized Access test - TEST --->"
          icon_emoji: ":bell:"
          channel: "educ-automation-failures"
          url: ${{ secrets.ROCKETCHAT_WEBHOOK_FAILURES }}