name: Update student detials Test Environment
on:
  repository_dispatch:
    types: [update-student-details-test-environment]
  workflow_dispatch: 
jobs:
  Regression:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - run: npm install

      - run: npm run updateStudentDetails
        if: ${{ always() }}
        env:
          PEN_ENVIRONMENT: ${{ secrets.TEST_ENVIRONMENT }}
          PEN_NAMESPACE: ${{ secrets.PEN_NAMESPACE }}
          IDIR_ADMIN_USER: ${{ secrets.IDIR_ADMIN_USER }}
          IDIR_ADMIN_PASS: ${{ secrets.IDIR_ADMIN_PASS }}
